name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
          go get github.com/axw/gocov/gocov
          go get github.com/mattn/goveralls
          go get ./cmd/pinyin

      - name: Test
        run: |
          go run cmd/pinyin/main.go abc
          go run cmd/pinyin/main.go -s zhao abc
          echo "abc" | go run cmd/pinyin/main.go
          echo "abc" > abc.txt && go run cmd/pinyin/main.go < abc.txt
